name: scaff
description: scaff (scaffold generator) is a simple command-line based utility for generating Dart and Flutter components from template files.
version: 1.0.2
homepage: https://github.com/ganeshrvel/pub-scaff

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  path: ^1.6.0
  mustache: ^1.1.1
  prompts: ^1.3.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
