name: scaff
description: Scaffold Generator for Dart and Flutter.
version: 1.0.0
homepage: https://github.com/ganeshrvel/pub-scaff

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  path: ^1.6.0
  args: ^1.5.2
  mustache: ^1.1.1
  prompts: ^1.3.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
