name: scaff
description: scaff (scaffold generator) is a simple command-line utility for generating Dart and Flutter components from template files.
version: 2.0.1
homepage: https://github.com/ganeshrvel/pub-scaff

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.1
  path: ^1.8.3
  mustache_template: ^2.0.0
  prompts: ^2.0.0

dev_dependencies:
  lint: ^2.1.2
